=== thelia/thelia/core/lib/Thelia/Core/DependencyInjection/Loader/schema/dic/config/thelia-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns="http://thelia.net/schema/dic/config"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://thelia.net/schema/dic/config"
            elementFormDefault="qualified">

    <xsd:element name="config" type="config" />

    <xsd:complexType name="config">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="loops" type="loops" />
            <xsd:element name="filters" type="filters" />
            <xsd:element name="templateDirectives" type="templateDirectives" />
            <xsd:element name="services" type="services" />
            <xsd:element name="parameters" type="parameters"/>
            <xsd:element name="commands" type="commands"/>
            <xsd:element name="forms" type="forms" />
            <xsd:element name="routing" type="routing" />
            <xsd:element name="hooks" type="hooks" />
            <xsd:element name="export_categories" type="export_categories" />
            <xsd:element name="exports" type="exports" />
            <xsd:element name="import_categories" type="import_categories" />
            <xsd:element name="imports" type="imports" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="parameters">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="parameter" type="parameter" />
        </xsd:choice>
        <xsd:attribute name="type" type="parameter_type" />
        <xsd:attribute name="key" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="parameter" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="parameter" type="parameter" />
        </xsd:choice>
        <xsd:attribute name="type" type="parameter_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="on-invalid" type="invalid_sequence" />
    </xsd:complexType>

    <xsd:simpleType name="parameter_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="collection" />
            <xsd:enumeration value="service" />
            <xsd:enumeration value="string" />
            <xsd:enumeration value="constant" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="invalid_sequence">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="null" />
            <xsd:enumeration value="ignore" />
            <xsd:enumeration value="exception" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="routing">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="file" type="file"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="file">
        <xsd:attribute name="path" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="loops">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="loop" type="loop"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="loop">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="commands">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="command" type="command"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="command">
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="forms">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="form" type="form" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="form">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="filters">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="filter" type="filter" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="filter">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="templateDirectives">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="templateDirective" type="templateDirective" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="templateDirective">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="services">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Enclosing element for the definition of all services
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="service" type="service" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="hooks">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Enclosing element for the definition of all hooks
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="hook" type="hook" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="service">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="factory" type="factory" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="configurator" type="configurator" minOccurs="0" maxOccurs="1" />
            <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="scope" type="xsd:string" />
        <xsd:attribute name="public" type="boolean" />
        <xsd:attribute name="synthetic" type="boolean" />
        <xsd:attribute name="abstract" type="boolean" />
        <xsd:attribute name="factory" type="xsd:string" />
        <xsd:attribute name="alias" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
        <xsd:attribute name="shared" type="xsd:boolean" />
        <xsd:attribute name="decorates" type="xsd:string" />
        <xsd:attribute name="decoration-on-invalid" type="invalid_decorated_service_sequence" />
        <xsd:attribute name="decoration-inner-name" type="xsd:string" />
        <xsd:attribute name="decoration-priority" type="xsd:integer" />
    </xsd:complexType>

    <xsd:simpleType name="invalid_decorated_service_sequence">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="null" />
            <xsd:enumeration value="ignore" />
            <xsd:enumeration value="exception" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="hook">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="configurator" type="configurator" minOccurs="0" maxOccurs="1" />
            <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="tag" type="hook_tag" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="scope" type="xsd:string" />
        <xsd:attribute name="public" type="boolean" />
        <xsd:attribute name="synthetic" type="boolean" />
        <xsd:attribute name="abstract" type="boolean" />
        <xsd:attribute name="factory" type="xsd:string" />
        <xsd:attribute name="alias" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
        <xsd:attribute name="event" type="xsd:string" />
        <xsd:attribute name="type" type="hook_type" />
        <xsd:attribute name="active" type="hook_active" />
    </xsd:complexType>

    <xsd:complexType name="hook_tag">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="event" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
        <xsd:attribute name="type" type="hook_type" />
        <xsd:attribute name="active" type="hook_active" />
        <xsd:attribute name="templates" type="xsd:string" />
    </xsd:complexType>

    <xsd:simpleType name="hook_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="fo" />
            <xsd:enumeration value="front" />
            <xsd:enumeration value="frontoffice" />
            <xsd:enumeration value="bo" />
            <xsd:enumeration value="back" />
            <xsd:enumeration value="backoffice" />
            <xsd:enumeration value="pdf" />
            <xsd:enumeration value="email" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hook_active">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="0" />
            <xsd:enumeration value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tag">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:anyAttribute namespace="##any" processContents="lax" />
    </xsd:complexType>

    <xsd:complexType name="property" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="type" type="argument_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="on-invalid" type="xsd:string" />
        <xsd:attribute name="strict" type="boolean" />
    </xsd:complexType>

    <xsd:complexType name="argument" mixed="true">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="type" type="argument_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="index" type="xsd:integer" />
        <xsd:attribute name="on-invalid" type="xsd:string" />
        <xsd:attribute name="strict" type="boolean" />
    </xsd:complexType>

    <xsd:complexType name="factory" mixed="true">
        <xsd:attribute name="service" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="call" mixed="true">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="method" type="xsd:string" />
    </xsd:complexType>

    <xsd:simpleType name="argument_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="collection" />
            <xsd:enumeration value="service" />
            <xsd:enumeration value="string" />
            <xsd:enumeration value="constant" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="boolean">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(%.+%|true|false)" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="configurator">
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="service" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
        <xsd:attribute name="function" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="export_categories">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="export_category" type="export_category"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="export_category">
        <xsd:choice maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="title" type="export_category_title" />
        </xsd:choice>

        <xsd:attribute name="id" use="required" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="export_category_title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="locale" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="exports">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="export" type="export"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="export">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="export_descriptive" type="export_descriptive" />
        </xsd:choice>

        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="category_id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="export_descriptive">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element name="title" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="description" type="xsd:string" />
        </xsd:sequence>

        <xsd:attribute name="locale" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="import_categories">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="import_category" type="import_category"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="import_category">
        <xsd:choice maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="title" type="import_category_title" />
        </xsd:choice>

        <xsd:attribute name="id" use="required" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="import_category_title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="locale" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="imports">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="import" type="import"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="import">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="import_descriptive" type="import_descriptive" />
        </xsd:choice>

        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="category_id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="import_descriptive">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element name="title" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="description" type="xsd:string" />
        </xsd:sequence>

        <xsd:attribute name="locale" type="xsd:string" use="required" />
    </xsd:complexType>

</xsd:schema>

=== thelia/thelia/core/lib/Thelia/Config/Resources/routing.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <parameters>
        <parameter key="router.request_context.class">Symfony\Component\Routing\RequestContext</parameter>
        <parameter key="router.null_generator.class">Thelia\Routing\NullUrlGenerator</parameter>
        <parameter key="router.dynamicRouter.class">Symfony\Cmf\Component\Routing\DynamicRouter</parameter>
        <parameter key="router.chainRouter.class">Symfony\Cmf\Component\Routing\ChainRouter</parameter>
        <parameter key="router.class">Symfony\Component\Routing\Router</parameter>
        <parameter key="router.xmlFileName">routing.xml</parameter>
    </parameters>

    <services>
        <service id="Thelia\Core\EventListener\ViewListener">
            <argument type="service" id="thelia.parser.resolver"/>
            <argument type="service" id="thelia.template_helper"/>
            <argument type="service" id="request_stack"/>
            <argument type="service" id="event_dispatcher"/>
            <argument type="service" id="router.chainRequest"/>
            <tag name="kernel.event_subscriber"/>
        </service>
        <service id="thelia.listener.view" alias="Thelia\Core\EventListener\ViewListener"/>

        <service id="controller.default" class="Thelia\Controller\DefaultController" public="true"/>

        <service id="thelia.admin.base_controller" class="Thelia\Admin\Controller\BaseAdminController">
       		<argument type="service" id="thelia.parser.resolver"/>
        </service>


        <service id="request.context" class="%router.request_context.class%" public="true" />


        <service id="router.fileLocator" class="Symfony\Component\Config\FileLocator" public="true">
            <argument>%thelia.core_dir%/Config/Resources/routing</argument>
        </service>

        <service id="router.xmlLoader" class="Symfony\Component\Routing\Loader\XmlFileLoader">
            <argument type="service" id="router.fileLocator"/>
        </service>

        <service id="router.module.fileLocator" class="Symfony\Component\Config\FileLocator">
            <argument>%thelia.module_dir%</argument>
        </service>

        <service id="router.module.xmlLoader" class="Symfony\Component\Routing\Loader\XmlFileLoader">
            <argument type="service" id="router.module.fileLocator"/>
        </service>

        <service id="router.admin" class="%router.class%" public="true">
            <argument type="service" id="router.xmlLoader"/>
            <argument>admin.xml</argument>
            <argument type="collection">
                <argument key="cache_dir">%kernel.cache_dir%</argument>
                <argument key="debug">%kernel.debug%</argument>
            </argument>
            <argument type="service" id="request.context"/>
            <tag name="router.register" priority="0"/>
        </service>

        <service id="router.rewrite" class="Thelia\Core\Routing\RewritingRouter" />


        <service id="thelia.loader.template_attributes" class="Thelia\Core\Routing\TemplateAttributeLoader" public="false">
          <tag name="routing.loader" priority="254"/>
        </service>
        <service id="thelia.loader.module_attributes" class="Thelia\Core\Routing\ModuleAttributeLoader" public="false">
          <tag name="routing.loader" priority="254"/>
        </service>
        <service id="thelia.loader.module_annotations" class="Thelia\Core\Routing\ModuleAnnotationLoader" public="false">
          <tag name="routing.loader" priority="253" />
        </service>
        <service id="thelia.loader.module_xml" class="Thelia\Core\Routing\ModuleXmlLoader" public="false">
          <argument>%env(APP_ENV)%</argument>
          <tag name="routing.loader" priority="252" />
        </service>

        <service id="router.chainRequest" class="%router.chainrouter.class%">
            <call method="setContext">
                <argument type="service" id="request.context"/>
            </call>
        </service>

        <service id="listener.router" class="Symfony\Component\HttpKernel\EventListener\RouterListener">
            <tag name="kernel.event_subscriber"/>
            <argument type="service" id="router.chainRequest"/>
            <argument type="service" id="request_stack"/>
        </service>
  </services>

</config>

=== thelia/thelia/local/modules/VirtualProductDelivery/Config/config.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <services>
        <service id="virtualproductdelivery.events" class="VirtualProductDelivery\EventListeners\VirtualProductEvents" scope="request">
            <tag name="kernel.event_subscriber"/>
        </service>
        <service id="virtualproductdelivery.mail" class="VirtualProductDelivery\EventListeners\SendMail" scope="request">
            <argument type="service" id="thelia.parser" />
            <argument type="service" id="mailer"/>
            <tag name="kernel.event_subscriber"/>
        </service>
    </services>

    <hooks>
        <hook id="virtualproductdelivery.hook" class="VirtualProductDelivery\Hook\HookManager" scope="request">
            <tag name="hook.event_listener" event="order-invoice.delivery-address" type="front" method="onDeliveryAddress" />
            <tag name="hook.event_listener" event="account-order.after-products" type="front"/>
            <tag name="hook.event_listener" event="delivery.delivery-address" type="pdf" method="onDeliveryAddress" />
            <tag name="hook.event_listener" event="invoice.delivery-address" type="pdf" method="onDeliveryAddress" />
        </hook>
    </hooks>

</config>

=== thelia/thelia/core/lib/Thelia/Config/Resources/coupon.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">


    <services>


        <!-- Coupon module -->
        <service id="thelia.facade" class="Thelia\Coupon\BaseFacade">
            <argument type="service" id="service_container" />
        </service>
        <service id="thelia.coupon.manager" class="Thelia\Coupon\CouponManager">
            <argument type="service" id="service_container" />
        </service>
        <service id="thelia.coupon.factory" class="Thelia\Coupon\CouponFactory">
            <argument type="service" id="service_container" />
        </service>

        <service id="thelia.coupon.type.remove_x_amount" class="Thelia\Coupon\Type\RemoveXAmount">
            <argument type="service" id="thelia.facade" />
            <tag name="thelia.coupon.addCoupon"/>
        </service>
        <service id="thelia.coupon.type.remove_x_percent" class="Thelia\Coupon\Type\RemoveXPercent">
            <argument type="service" id="thelia.facade" />
            <tag name="thelia.coupon.addCoupon"/>
        </service>


        <!-- Condition module -->
        <service id="thelia.condition.factory" class="Thelia\Condition\ConditionFactory">
            <argument type="service" id="service_container" />
        </service>
        <service id="thelia.condition.validator" class="Thelia\Condition\ConditionEvaluator">
        </service>
        <service id="thelia.condition.match_for_everyone" class="Thelia\Condition\Implementation\MatchForEveryone">
            <argument type="service" id="thelia.facade" />
            <tag name="thelia.coupon.addCondition"/>
        </service>
        <service id="thelia.condition.match_for_total_amount" class="Thelia\Condition\Implementation\MatchForTotalAmount">
            <argument type="service" id="thelia.facade" />
            <tag name="thelia.coupon.addCondition"/>
        </service>
        <service id="thelia.condition.match_for_x_articles" class="Thelia\Condition\Implementation\MatchForXArticles">
            <argument type="service" id="thelia.facade" />
            <tag name="thelia.coupon.addCondition"/>
        </service>




    </services>

</config>

=== thelia/thelia/core/lib/Thelia/Config/Resources/form-api.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <forms>
        <form name="thelia.api.empty" class="Thelia\Form\Api\ApiEmptyForm" />

        <!-- Forms for Customer -->
        <form name="thelia.api.customer.create" class="Thelia\Form\Api\Customer\CustomerCreateForm"/>
        <form name="thelia.api.customer.update" class="Thelia\Form\Api\Customer\CustomerUpdateForm"/>
        <form name="thelia.api.customer.login" class="Thelia\Form\Api\Customer\CustomerLogin"/>

        <!-- Forms for Category -->
        <form name="thelia.api.category.create" class="Thelia\Form\Api\Category\CategoryCreationForm"/>
        <form name="thelia.api.category.update" class="Thelia\Form\Api\Category\CategoryModificationForm"/>


        <!-- Product sale elements form -->
        <form name="thelia.api.product_sale_elements" class="Thelia\Form\Api\ProductSaleElements\ProductSaleElementsForm" />

    </forms>
</config>

=== thelia/thelia/local/modules/Colissimo/Config/config.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <loops>
        <loop class="Colissimo\Loop\Price" name="colissimo"/>
    </loops>

    <forms>
        <!--
        <form name="MyFormName" class="MyModule\Form\MySuperForm" />
        -->
    </forms>

    <commands>
        <!--
        <command class="MyModule\Command\MySuperCommand" />
        -->
    </commands>

    <templateDirectives>
        <!-- Sample definition
        <templateDirectives class="MyModule\Directive\MyTemplateDirective" name="my_filter"/>
        -->
    </templateDirectives>

    <services>
        <service id="send.colissimo.mail" class="Colissimo\Listener\SendMail" scope="request">
            <argument type="service" id="thelia.parser" />
            <argument type="service" id="mailer"/>
            <tag name="kernel.event_subscriber"/>
        </service>
    </services>
</config>
