=== thelia/thelia/core/lib/Thelia/Core/DependencyInjection/Loader/schema/dic/config/thelia-1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns="http://thelia.net/schema/dic/config"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://thelia.net/schema/dic/config"
            elementFormDefault="qualified">

    <xsd:element name="config" type="config" />

    <xsd:complexType name="config">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="loops" type="loops" />
            <xsd:element name="filters" type="filters" />
            <xsd:element name="templateDirectives" type="templateDirectives" />
            <xsd:element name="services" type="services" />
            <xsd:element name="parameters" type="parameters"/>
            <xsd:element name="commands" type="commands"/>
            <xsd:element name="forms" type="forms" />
            <xsd:element name="routing" type="routing" />
            <xsd:element name="hooks" type="hooks" />
            <xsd:element name="export_categories" type="export_categories" />
            <xsd:element name="exports" type="exports" />
            <xsd:element name="import_categories" type="import_categories" />
            <xsd:element name="imports" type="imports" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="parameters">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="parameter" type="parameter" />
        </xsd:choice>
        <xsd:attribute name="type" type="parameter_type" />
        <xsd:attribute name="key" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="parameter" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="parameter" type="parameter" />
        </xsd:choice>
        <xsd:attribute name="type" type="parameter_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="on-invalid" type="invalid_sequence" />
    </xsd:complexType>

    <xsd:simpleType name="parameter_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="collection" />
            <xsd:enumeration value="service" />
            <xsd:enumeration value="string" />
            <xsd:enumeration value="constant" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="invalid_sequence">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="null" />
            <xsd:enumeration value="ignore" />
            <xsd:enumeration value="exception" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="routing">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="file" type="file"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="file">
        <xsd:attribute name="path" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="loops">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="loop" type="loop"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="loop">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="commands">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="command" type="command"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="command">
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="forms">
        <xsd:choice minOccurs="0" maxOccurs="unbounded" >
            <xsd:element name="form" type="form" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="form">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="filters">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="filter" type="filter" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="filter">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="templateDirectives">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="templateDirective" type="templateDirective" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="templateDirective">
        <xsd:attribute name="class" type="xsd:string" use="required" />
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="services">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Enclosing element for the definition of all services
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="service" type="service" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="hooks">
        <xsd:annotation>
            <xsd:documentation><![CDATA[
        Enclosing element for the definition of all hooks
      ]]></xsd:documentation>
        </xsd:annotation>
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="hook" type="hook" />
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="service">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="factory" type="factory" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="configurator" type="configurator" minOccurs="0" maxOccurs="1" />
            <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="tag" type="tag" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="scope" type="xsd:string" />
        <xsd:attribute name="public" type="boolean" />
        <xsd:attribute name="synthetic" type="boolean" />
        <xsd:attribute name="abstract" type="boolean" />
        <xsd:attribute name="factory" type="xsd:string" />
        <xsd:attribute name="alias" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
        <xsd:attribute name="shared" type="xsd:boolean" />
        <xsd:attribute name="decorates" type="xsd:string" />
        <xsd:attribute name="decoration-on-invalid" type="invalid_decorated_service_sequence" />
        <xsd:attribute name="decoration-inner-name" type="xsd:string" />
        <xsd:attribute name="decoration-priority" type="xsd:integer" />
    </xsd:complexType>

    <xsd:simpleType name="invalid_decorated_service_sequence">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="null" />
            <xsd:enumeration value="ignore" />
            <xsd:enumeration value="exception" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="hook">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="1" />
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="configurator" type="configurator" minOccurs="0" maxOccurs="1" />
            <xsd:element name="call" type="call" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="tag" type="hook_tag" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="scope" type="xsd:string" />
        <xsd:attribute name="public" type="boolean" />
        <xsd:attribute name="synthetic" type="boolean" />
        <xsd:attribute name="abstract" type="boolean" />
        <xsd:attribute name="factory" type="xsd:string" />
        <xsd:attribute name="alias" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
        <xsd:attribute name="event" type="xsd:string" />
        <xsd:attribute name="type" type="hook_type" />
        <xsd:attribute name="active" type="hook_active" />
    </xsd:complexType>

    <xsd:complexType name="hook_tag">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="event" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
        <xsd:attribute name="type" type="hook_type" />
        <xsd:attribute name="active" type="hook_active" />
        <xsd:attribute name="templates" type="xsd:string" />
    </xsd:complexType>

    <xsd:simpleType name="hook_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="fo" />
            <xsd:enumeration value="front" />
            <xsd:enumeration value="frontoffice" />
            <xsd:enumeration value="bo" />
            <xsd:enumeration value="back" />
            <xsd:enumeration value="backoffice" />
            <xsd:enumeration value="pdf" />
            <xsd:enumeration value="email" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hook_active">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="0" />
            <xsd:enumeration value="1" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="tag">
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:anyAttribute namespace="##any" processContents="lax" />
    </xsd:complexType>

    <xsd:complexType name="property" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="1">
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="type" type="argument_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="name" type="xsd:string" />
        <xsd:attribute name="on-invalid" type="xsd:string" />
        <xsd:attribute name="strict" type="boolean" />
    </xsd:complexType>

    <xsd:complexType name="argument" mixed="true">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="type" type="argument_type" />
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="index" type="xsd:integer" />
        <xsd:attribute name="on-invalid" type="xsd:string" />
        <xsd:attribute name="strict" type="boolean" />
    </xsd:complexType>

    <xsd:complexType name="factory" mixed="true">
        <xsd:attribute name="service" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="call" mixed="true">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="argument" type="argument" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="service" type="service" />
        </xsd:choice>
        <xsd:attribute name="method" type="xsd:string" />
    </xsd:complexType>

    <xsd:simpleType name="argument_type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="collection" />
            <xsd:enumeration value="service" />
            <xsd:enumeration value="string" />
            <xsd:enumeration value="constant" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="boolean">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="(%.+%|true|false)" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="configurator">
        <xsd:attribute name="id" type="xsd:string" />
        <xsd:attribute name="service" type="xsd:string" />
        <xsd:attribute name="class" type="xsd:string" />
        <xsd:attribute name="method" type="xsd:string" />
        <xsd:attribute name="function" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="export_categories">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="export_category" type="export_category"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="export_category">
        <xsd:choice maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="title" type="export_category_title" />
        </xsd:choice>

        <xsd:attribute name="id" use="required" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="export_category_title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="locale" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="exports">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="export" type="export"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="export">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="export_descriptive" type="export_descriptive" />
        </xsd:choice>

        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="category_id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="export_descriptive">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element name="title" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="description" type="xsd:string" />
        </xsd:sequence>

        <xsd:attribute name="locale" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="import_categories">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="import_category" type="import_category"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="import_category">
        <xsd:choice maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="title" type="import_category_title" />
        </xsd:choice>

        <xsd:attribute name="id" use="required" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="import_category_title">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="locale" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="imports">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="import" type="import"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="import">
        <xsd:choice minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="import_descriptive" type="import_descriptive" />
        </xsd:choice>

        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="class" type="xsd:string" use="required"/>
        <xsd:attribute name="category_id" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="import_descriptive">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element name="title" type="xsd:string" />
            <xsd:element minOccurs="0" maxOccurs="1" name="description" type="xsd:string" />
        </xsd:sequence>

        <xsd:attribute name="locale" type="xsd:string" use="required" />
    </xsd:complexType>

</xsd:schema>

=== thelia/thelia/core/lib/Thelia/Config/Resources/smarty-plugin.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <services>

        <!--  URL maganement -->

        <!--  The assets manager -->
        <service id="assetic.asset.manager" class="Thelia\Core\Template\Assets\AsseticAssetManager" >
            <argument>%kernel.debug%</argument>
        </service>

        <!-- Smarty parser plugins -->

        <service id="smarty.plugin.assets" class="Thelia\Core\Template\Smarty\Plugins\Assets" >
            <tag name="thelia.parser.register_plugin"/>

            <argument type="service" id="assetic.asset.manager" />
        </service>

        <service id="smarty.plugin.theliasyntax" class="Thelia\Core\Template\Smarty\Plugins\TheliaSyntax" >
            <tag name="thelia.parser.register_plugin"/>
        </service>

        <service id="smarty.plugin.format" class="Thelia\Core\Template\Smarty\Plugins\Format" scope="request">
            <argument type="service" id="request"/>
            <tag name="thelia.parser.register_plugin"/>
        </service>

        <service id="smarty.plugin.thelialoop" class="Thelia\Core\Template\Smarty\Plugins\TheliaLoop" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="service_container" />
            <call method="setLoopList">
                <argument>%thelia.parser.loops%</argument>
            </call>
        </service>

        <service id="smarty.plugin.cartpostage" class="Thelia\Core\Template\Smarty\Plugins\CartPostage" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="service_container" />
        </service>

        <service id="smarty.plugin.type" class="Thelia\Core\Template\Smarty\Plugins\Type" scope="request">
            <tag name="thelia.parser.register_plugin"/>
        </service>

        <service id="smart.plugin.form" class="Thelia\Core\Template\Smarty\Plugins\Form" scope="request">
            <tag name="thelia.parser.register_plugin"/>

            <argument type="service" id="request"/>
            <argument type="service" id="thelia.parser.context"/>
            <argument type="service" id="thelia.parser"/>

            <call method="setFormDefinition">
                <argument>%thelia.parser.forms%</argument>
            </call>
        </service>

        <service id="smarty.plugin.translation" class="Thelia\Core\Template\Smarty\Plugins\Translation" >
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="thelia.translator" />
        </service>

        <service id="smarty.plugin.module" class="Thelia\Core\Template\Smarty\Plugins\Module" scope="request">
            <argument>%kernel.debug%</argument>
            <argument type="service" id="request"/>
            <tag name="thelia.parser.register_plugin"/>
        </service>

        <service id="smarty.url.module" class="Thelia\Core\Template\Smarty\Plugins\UrlGenerator" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="request"/>
            <argument type="service" id="thelia.token_provider"/>
        </service>

        <service id="smarty.plugin.security" class="Thelia\Core\Template\Smarty\Plugins\Security" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="request" />
            <argument type="service" id="thelia.securityContext" />
        </service>

        <service id="smarty.plugin.dataAccess" class="Thelia\Core\Template\Smarty\Plugins\DataAccessFunctions" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="request" />
            <argument type="service" id="thelia.securityContext" />
            <argument type="service" id="thelia.taxEngine" />
            <argument type="service" id="thelia.parser.context"/>
            <argument type="service" id="event_dispatcher"/>
        </service>

        <service id="smarty.plugin.adminUtilities" class="Thelia\Core\Template\Smarty\Plugins\AdminUtilities" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="thelia.securityContext" />
        </service>

        <service id="smarty.plugin.flashMessage" class="Thelia\Core\Template\Smarty\Plugins\FlashMessage" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="request" />
        </service>

        <service id="smarty.plugin.esi" class="Thelia\Core\Template\Smarty\Plugins\Esi" scope="request">
            <tag name="thelia.parser.register_plugin"/>
            <argument type="service" id="fragment.renderer.esi" />
            <argument type="service" id="request" />
        </service>

        <service id="smarty.plugin.hook" class="Thelia\Core\Template\Smarty\Plugins\Hook" scope="request">
            <argument>%kernel.debug%</argument>
            <tag name="thelia.parser.register_plugin"/>
            <!--
            <argument type="service" id="request" />
            <argument type="service" id="thelia.securityContext" />
            <argument type="service" id="thelia.taxEngine" />
            <argument type="service" id="thelia.parser.context"/>
            -->
            <argument type="service" id="event_dispatcher"/>
        </service>

    </services>

</config>

=== thelia/thelia/core/lib/Thelia/Config/Resources/test.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <parameters>
        <parameter key="test.client.class">Thelia\Core\HttpKernel\Client</parameter>
        <parameter key="test.client.parameters" type="collection"></parameter>
        <parameter key="test.client.history.class">Symfony\Component\BrowserKit\History</parameter>
        <parameter key="test.client.cookiejar.class">Symfony\Component\BrowserKit\CookieJar</parameter>
    </parameters>

    <services>
        <service id="test.client" class="%test.client.class%">
            <argument type="service" id="kernel" />
            <argument>%test.client.parameters%</argument>
            <argument type="service" id="test.client.history" />
            <argument type="service" id="test.client.cookiejar" />
        </service>

        <service id="test.client.history" class="%test.client.history.class%" />

        <service id="test.client.cookiejar" class="%test.client.cookiejar.class%" />

    </services>

</config>

=== thelia/thelia/core/lib/Thelia/Config/Resources/stack.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <services>
        <service id="session.middleware" class="Thelia\Core\Stack\SessionMiddleware">
            <argument type="service" id="event_dispatcher" />
            <argument>%kernel.cache_dir%</argument>
            <argument>%kernel.debug%</argument>
            <argument>%kernel.environment%</argument>

            <tag name="stack_middleware" priority="1000" />
        </service>
        <service id="initParam.middleware" class="Thelia\Core\Stack\ParamInitMiddleware">
            <argument type="service" id="thelia.url.manager" />
            <argument type="service" id="thelia.translator" />
            <argument type="service" id="event_dispatcher" />

            <tag name="stack_middleware" priority="999" />
        </service>
    </services>
</config>

=== thelia/thelia/local/modules/HookSocial/Config/config.xml
<?xml version="1.0" encoding="UTF-8" ?>

<config xmlns="http://thelia.net/schema/dic/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://thelia.net/schema/dic/config http://thelia.net/schema/dic/config/thelia-1.0.xsd">

    <loops>
    </loops>

    <forms>
        <form name="hooksocial.configuration.form" class="HookSocial\Form\Configuration" />
    </forms>

    <commands>
    </commands>

    <hooks>
        <hook id="hooksocial.hook.front" class="HookSocial\Hook\FrontHook" scope="request">
            <tag name="hook.event_listener" event="main.footer-body" />
        </hook>
        <hook id="hooksocial.hook.back" class="HookSocial\Hook\BackHook" scope="request">
            <tag name="hook.event_listener" event="module.configuration" type="back" method="onModuleConfiguration" />
            <tag name="hook.event_listener" event="module.config-js" type="back" method="onModuleConfigurationJS" />
        </hook>
    </hooks>

</config>
